language: node_js
node_js:
- 9
- 8
matrix:
  allow_failures:
  - node_js: 9
branches:
  only:
  - master
  - "/^v\\d.*$/"
deploy:
  provider: npm
  email: baderbuddy@gmail.com
  api_key:
    secure: VRrFZqsxjfx5XrWBMAdiLvdw+/SmEMJYfVMyaBbe+49his6ZPrLeEe/zo7mH7Sg5e05NToc8s17zZJqfOqm6FvSvF7BUXoiaRnSYX4t9HNusq6SEJWKI4XiIaWdkDYxfZ68uGOuxQKJDgTqFIShQTyPV6gPMfmC0gVIa3eAolvo=
  on:
    tags: true
    repo: deepsweet/mustache-loader
